
tables:
  producerCode:
    tableName: ori_pak_producer
    prefix: pro
    on: 'producerCode = pro.cno'
    cols:
      - columnName: name
        remark: 生产商描述
        javaFieldName: producerName

  matnr:
    tableName: mdm_mara
    prefix: mara
    on: 'matnr = mara.mat_code'
    cols:
      - columnName: mat_name
        remark: 物料描述
        selectSql: rtrim(mara.mat_name) as maktx
        javaFieldName: maktx

  supplierCode:
    tableName: mdm_supplier_base
    prefix: supp
    on: 'supplierCode = supp.supplierCode'
    cols:
      -
        columnName: supplierName
        remark: 供应商描述

  supplierNo:
    tableName: mdm_supplier_base
    prefix: supp
    on: 'supplierNo = supp.supplierCode'
    cols:
      -
        columnName: supplierName
        remark: 供应商描述
  createAcc:
    tableName: hr_employee
    prefix: hr1
    on: 'createAcc = hr1.one_account'
    cols:
      - columnName: emp_name
        remark: 创建人
        javaFieldName: creator


  updateAcc:
    tableName: hr_employee
    prefix: hr2
    on: 'updateAcc = hr2.one_account'
    cols:
      - columnName: emp_name
        remark: 修改人
        javaFieldName: modifier

  account:
    tableName: hr_employee
    prefix: hr
    on: 'account = hr.one_account'
    cols:
      -
        columnName: emp_name
        remark: 姓名
        javaFieldName: userChName

  vtcode:
    tableName: qc_verifystang
    prefix: vt
    on: 'vtcode = vt.cno'
    cols:
      -
        columnName: cname
        remark: 特性描述
        javaFieldName: vtname
        selectSql: rtrim(vt.cname) as vtname

  factoryMaraGroup:
    tableName: factory_material_group
    prefix: maraGp
    on: 'factoryMaraGroup = maraGp.code'
    cols:
      -
        columnName: descr
        remark: 物料组描述
        javaFieldName: groupDescr
        selectSql: rtrim(descr) as groupDescr

  factoryRptId:
    tableName: factory_report_h
    prefix: h
    on: 'factoryRptId = h.id'
    cols:
      -
        columnName: aufnr
        remark: 订单号
        javaFieldName: aufnr
        selectSql: aufnr
      -
        columnName: werk
        remark: 工厂
        javaFieldName: werk
        selectSql: werk
      -
        columnName: matnr
        remark: 物料编码
      -
        columnName: maktx
        remark: 物料描述
      -
        columnName: productDate
        remark: 生产日期
        selectSql: cast(productDate as date) as productDate

  payKostl:
    tableName: sap_cskt
    prefix: pay
    on: 'payKostl = pay.kostl'
    cols:
      - columnName: ktext
        remark: 支出方成本中心描述
        javaFieldName: payKtext

      - columnName: budgetOrgName
        remark: 支出方
        javaFieldName: payCenter

  revenueKostl:
    tableName: sap_cskt
    prefix: revenue
    on: 'revenueKostl = revenue.kostl'
    cols:
      - columnName: ktext
        remark: 收入方成本中心描述
        javaFieldName: revenueKtext

      - columnName: budgetOrgName
        remark: 收入方
        javaFieldName: revenueCenter