
tables:
  producerCode:
    tableName: ori_pak_producer
    prefix: pro
    on: 'producerCode = pro.cno'
    cols:
      - columnName: name
        remark: 生产商描述
        javaFieldName: producerName

  matnr:
    tableName: mdm_mara
    prefix: mara
    on: 'matnr = mara.mat_code'
    cols:
      - columnName: mat_name
        remark: 物料描述
        selectSql: rtrim(mara.mat_name) as maktx
        javaFieldName: maktx

  supplierCode:
    tableName: mdm_supplier_base
    prefix: supp
    on: 'supplierCode = supp.supplierCode'
    cols:
      -
        columnName: supplierName
        remark: 供应商描述

  supplierNo:
    tableName: mdm_supplier_base
    prefix: supp
    on: 'supplierNo = supp.supplierCode'
    cols:
      -
        columnName: supplierName
        remark: 供应商描述

  account:
    tableName: hr_employee
    prefix: hr
    on: 'account = hr.one_account'
    cols:
      -
        columnName: emp_name
        remark: 姓名
        javaFieldName: userChName

  vtcode:
    tableName: qc_verifystang
    prefix: vt
    on: 'vtcode = vt.cno'
    cols:
      -
        columnName: cname
        remark: 特性描述
        javaFieldName: vtname
        selectSql: rtrim(vt.cname) as vtname
